# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-firebase-firebase-multi-platform-application
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Firebase Multi-Platform Application Module
    source:
      repo: https://github.com/TrCaM/terraform-google-firebase.git
      sourceType: git
      dir: /modules/firebase_multi_platform_application
    actuationTool:
      flavor: Terraform
      version: ">= 1.3"
    description: {}
    icon: assets/icon.png
  content:
    examples:
      - name: firebase_multi_platform_app
        location: examples/firebase_multi_platform_app
  interfaces:
    variables:
      - name: project_id
        description: The GCP project ID to initialize Firebase in.
        varType: string
        required: true
      - name: display_name
        description: The display name for all apps in this instance.
        varType: string
        required: true
      - name: web_app
        description: Configuration for a Firebase Web App. Set to null to skip.
        varType: |-
          object({
              api_key_id = optional(string)
            })
      - name: android_app
        description: Configuration for a Firebase Android App. Set to null to skip.
        varType: |-
          object({
              package_name  = string
              sha256_hashes = optional(list(string))
            })
      - name: apple_app
        description: Configuration for a Firebase Apple (iOS) App. Set to null to skip.
        varType: |-
          object({
              bundle_id = string
              team_id   = optional(string)
            })
    outputs:
      - name: android_config
        description: The google-services.json content for the Android App.
      - name: app_ids
        description: Map of platform names to their respective Firebase App IDs.
      - name: ios_config
        description: The GoogleService-Info.plist content for the Apple App.
      - name: project_id
        description: The project ID.
      - name: web_config
        description: The configuration snippet for the Firebase Web App.
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 5.0, < 8.0"
      - source: hashicorp/google-beta
        version: ">= 5.0, < 8.0"
